/**
 * Shared institutional print/PDF layout for SMS Oriximiná.
 * All documents generated by the system use this template
 * to ensure consistent branding across screen, PDF, and print.
 *
 * Supports 3 logos (esquerda / central acima do texto / direita),
 * tipografia configurável, margens A4 ajustáveis, bloco institucional
 * de até 4 linhas, e bloco de carimbo profissional padronizado.
 */

import { supabase } from '@/integrations/supabase/client';
import logoSmsFallback from '@/assets/logo-sms-oriximina.jpeg';
import logoCerFallback from '@/assets/logo-cer-ii.png';

export interface DocumentTypography {
  fonte: string;          // 'Arial' | 'Times New Roman' | 'Calibri' | 'Inter'
  tamanhoBase: number;    // 10..14 (corpo)
  tamanhoTitulo: number;  // 14..20
  espacamento: number;    // 1 | 1.15 | 1.5
  alinhamento: 'justify' | 'left' | 'center';
}

export interface DocumentMargins {
  superior: number; // mm
  inferior: number;
  esquerda: number;
  direita: number;
}

export interface DocumentConfig {
  // 3 logos
  logoEsquerda: string;
  logoCentral: string;
  logoDireita: string;
  mostrarLogoCentral: boolean;
  // Bloco institucional (até 4 linhas)
  linha1: string;
  linha2: string;
  linha3: string;
  linha4: string;
  // Rodapé
  rodapeTexto: string;
  rodapeEndereco: string;
  // Tipografia + margens
  tipografia: DocumentTypography;
  margens: DocumentMargins;
  // Visuais
  mostrarLinhaDivisoria: boolean;
  mostrarRodape: boolean;
}

const DEFAULT_TYPOGRAPHY: DocumentTypography = {
  fonte: 'Arial',
  tamanhoBase: 11,
  tamanhoTitulo: 14,
  espacamento: 1.5,
  alinhamento: 'justify',
};

const DEFAULT_MARGINS: DocumentMargins = {
  superior: 20,
  inferior: 20,
  esquerda: 25,
  direita: 20,
};

export const DEFAULT_CONFIG: DocumentConfig = {
  logoEsquerda: '',
  logoCentral: '',
  logoDireita: '',
  mostrarLogoCentral: false,
  linha1: 'SECRETARIA MUNICIPAL DE SAÚDE DE ORIXIMINÁ',
  linha2: 'CENTRO ESPECIALIZADO EM REABILITAÇÃO NÍVEL II',
  linha3: '',
  linha4: '',
  rodapeTexto: '',
  rodapeEndereco: 'Rua Barão do Rio Branco, S/N, Santa Terezinha, Oriximiná-PA, 68270-000',
  tipografia: { ...DEFAULT_TYPOGRAPHY },
  margens: { ...DEFAULT_MARGINS },
  mostrarLinhaDivisoria: true,
  mostrarRodape: true,
};

let _cachedConfig: DocumentConfig | null = null;
let _cacheTimestamp = 0;
const CACHE_TTL = 60_000;

function mergeConfig(raw: any): DocumentConfig {
  if (!raw) return { ...DEFAULT_CONFIG };
  return {
    logoEsquerda: raw.cabecalho?.logoEsquerda || raw.cabecalho?.logoUrl || raw.logoEsquerda || '',
    logoCentral: raw.cabecalho?.logoCentral || raw.logoCentral || '',
    logoDireita: raw.cabecalho?.logoDireita || raw.logoDireita || '',
    mostrarLogoCentral: raw.cabecalho?.mostrarLogoCentral ?? raw.mostrarLogoCentral ?? false,
    linha1: raw.cabecalho?.linha1 || raw.linha1 || DEFAULT_CONFIG.linha1,
    linha2: raw.cabecalho?.linha2 || raw.linha2 || DEFAULT_CONFIG.linha2,
    linha3: raw.cabecalho?.linha3 || raw.linha3 || '',
    linha4: raw.cabecalho?.linha4 || raw.linha4 || '',
    rodapeTexto: raw.rodapeTexto || '',
    rodapeEndereco: raw.rodapeEndereco || DEFAULT_CONFIG.rodapeEndereco,
    tipografia: { ...DEFAULT_TYPOGRAPHY, ...(raw.tipografia || {}) },
    margens: { ...DEFAULT_MARGINS, ...(raw.margens || {}) },
    mostrarLinhaDivisoria: raw.mostrarLinhaDivisoria ?? true,
    mostrarRodape: raw.mostrarRodape ?? true,
  };
}

export async function loadDocumentConfig(): Promise<DocumentConfig> {
  if (_cachedConfig && Date.now() - _cacheTimestamp < CACHE_TTL) return _cachedConfig;
  try {
    const { data } = await supabase
      .from('system_config')
      .select('configuracoes')
      .eq('id', 'default')
      .maybeSingle();
    const cfg = (data?.configuracoes as any)?.config_impressao;
    _cachedConfig = mergeConfig(cfg);
  } catch {
    _cachedConfig = { ...DEFAULT_CONFIG };
  }
  _cacheTimestamp = Date.now();
  return _cachedConfig!;
}

export function invalidateDocumentConfigCache(): void {
  _cachedConfig = null;
  _cacheTimestamp = 0;
}

function resolveLogoUrl(configUrl: string, fallback: string): string {
  if (configUrl && (configUrl.startsWith('http') || configUrl.startsWith('/'))) return configUrl;
  return fallback;
}

/** Standard institutional CSS shared across all documents */
export function buildInstitutionalCSS(config?: DocumentConfig): string {
  const t = config?.tipografia || DEFAULT_TYPOGRAPHY;
  const m = config?.margens || DEFAULT_MARGINS;
  const fontFamily =
    t.fonte === 'Times New Roman' ? `'Times New Roman', Times, serif`
    : t.fonte === 'Calibri' ? `Calibri, 'Segoe UI', Arial, sans-serif`
    : t.fonte === 'Inter' ? `Inter, system-ui, Arial, sans-serif`
    : `Arial, 'Helvetica Neue', Helvetica, sans-serif`;

  return `
<style>
  @page {
    size: A4;
    margin: ${m.superior}mm ${m.direita}mm ${m.inferior}mm ${m.esquerda}mm;
    @bottom-center { content: "Página " counter(page) " de " counter(pages); font-size: 8pt; color: #666; }
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: ${fontFamily};
    padding: 0;
    color: #1a1a1a;
    font-size: ${t.tamanhoBase}pt;
    line-height: ${t.espacamento};
  }

  /* HEADER — 3 logos (esq | central acima do texto | dir) */
  .doc-header {
    display: grid;
    grid-template-columns: 110px 1fr 110px;
    align-items: center;
    gap: 12px;
    padding: 10px 0 12px;
    margin-bottom: 12px;
    ${config?.mostrarLinhaDivisoria !== false ? 'border-bottom: 2px solid #0369a1;' : ''}
  }
  .doc-header .logo-left,
  .doc-header .logo-right {
    display: flex; align-items: center; justify-content: center;
  }
  .doc-header .logo-left img,
  .doc-header .logo-right img {
    max-height: 70px;
    max-width: 100px;
    object-fit: contain;
    image-rendering: -webkit-optimize-contrast;
  }
  .doc-header .header-center {
    text-align: center;
    padding: 0 8px;
    display: flex; flex-direction: column; align-items: center; gap: 4px;
  }
  .doc-header .header-center .logo-central img {
    max-height: 60px;
    max-width: 180px;
    object-fit: contain;
    margin-bottom: 4px;
  }
  .doc-header h1 {
    font-size: ${Math.max(t.tamanhoBase + 1, 12)}pt;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #0c4a6e;
    margin: 0;
    line-height: 1.25;
  }
  .doc-header .subtitle {
    font-size: ${t.tamanhoBase}pt;
    color: #334155;
    line-height: 1.3;
  }
  .doc-header .extra-line {
    font-size: ${Math.max(t.tamanhoBase - 1, 9)}pt;
    color: #475569;
    line-height: 1.3;
  }
  .doc-title-bar {
    text-align: center;
    font-size: ${t.tamanhoTitulo}pt;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    color: #1a1a1a;
    margin: 6px 0 14px;
    padding: 6px 0;
    border-top: 1px solid #e2e8f0;
    border-bottom: 1px solid #e2e8f0;
  }
  .doc-emit {
    text-align: right;
    font-size: 8pt;
    color: #64748b;
    margin-bottom: 6px;
  }

  /* META INFO BAR */
  .doc-meta {
    font-size: ${Math.max(t.tamanhoBase - 1, 9)}pt;
    color: #334155;
    padding: 8px 12px;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 4px;
    margin-bottom: 14px;
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
  }
  .doc-meta strong { color: #1a1a1a; }

  /* CONTENT */
  .doc-content {
    text-align: ${t.alinhamento};
    text-justify: inter-word;
    font-size: ${t.tamanhoBase}pt;
    line-height: ${t.espacamento};
  }
  .doc-content p { margin-bottom: 8px; }

  /* SUMMARY CARDS */
  .summary { display: flex; gap: 8px; margin-bottom: 16px; flex-wrap: wrap; }
  .stat { background: #f0f9ff; border: 1px solid #bae6fd; padding: 8px 14px; border-radius: 6px; text-align: center; min-width: 85px; }
  .stat strong { display: block; font-size: 16pt; color: #0369a1; }
  .stat small { font-size: 8pt; color: #64748b; }

  /* SECTION TITLES */
  h2 {
    font-size: ${Math.max(t.tamanhoBase + 1, 12)}pt;
    color: #0369a1;
    margin: 16px 0 8px;
    padding-bottom: 4px;
    border-bottom: 1.5px solid #bae6fd;
    text-transform: uppercase;
    letter-spacing: 0.3px;
  }

  /* TABLES */
  table { width: 100%; border-collapse: collapse; margin-bottom: 14px; page-break-inside: auto; }
  thead { display: table-header-group; }
  tr { page-break-inside: avoid; page-break-after: auto; }
  th, td { border: 1px solid #d1d5db; padding: 5px 8px; text-align: left; font-size: ${Math.max(t.tamanhoBase - 1, 9)}pt; }
  th { background: #f1f5f9; font-weight: 600; color: #1a1a1a; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  tr:nth-child(even) { background: #fafafa; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

  /* FIELDS */
  .content-block { text-align: ${t.alinhamento}; text-justify: inter-word; }
  .field { margin-bottom: 10px; }
  .field-label { font-size: 9pt; text-transform: uppercase; color: #64748b; font-weight: 600; letter-spacing: 0.4px; }
  .field-value { font-size: ${t.tamanhoBase}pt; margin-top: 2px; color: #1a1a1a; }

  .section { margin-bottom: 14px; }
  .section-title { font-weight: 600; font-size: 10pt; text-transform: uppercase; color: #0369a1; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin-bottom: 6px; }
  .section-content { font-size: ${t.tamanhoBase}pt; line-height: ${t.espacamento}; white-space: pre-wrap; min-height: 18px; text-align: ${t.alinhamento}; }

  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 16px; padding: 12px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; }
  .info-label { font-weight: 600; font-size: 9pt; text-transform: uppercase; color: #64748b; }
  .info-value { font-size: ${t.tamanhoBase}pt; color: #1a1a1a; }

  /* SIGNATURE / CARIMBO */
  .signature { margin-top: 50px; text-align: center; }
  .signature-line { width: 320px; border-top: 1px solid #1e293b; margin: 0 auto 6px; }
  .signature .name { font-size: ${t.tamanhoBase}pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; }
  .signature .role,
  .signature .conselho,
  .signature .cbo,
  .signature .extra { font-size: ${Math.max(t.tamanhoBase - 1, 9)}pt; color: #334155; }

  .signature.pos-left { text-align: left; }
  .signature.pos-left .signature-line { margin-left: 0; }
  .signature.pos-right { text-align: right; }
  .signature.pos-right .signature-line { margin-right: 0; margin-left: auto; }

  .signature .assinatura-img { max-height: 70px; max-width: 220px; display: block; margin: 0 auto 4px; object-fit: contain; }
  .signature.pos-left .assinatura-img { margin-left: 0; }
  .signature.pos-right .assinatura-img { margin-right: 0; margin-left: auto; }

  .carimbo-img { max-height: 90px; max-width: 240px; object-fit: contain; display: block; margin: 8px auto 0; }
  .signature.pos-left .carimbo-img { margin-left: 0; }
  .signature.pos-right .carimbo-img { margin-right: 0; margin-left: auto; }

  /* FOOTER */
  .doc-footer {
    margin-top: 30px;
    padding-top: 8px;
    border-top: 1.5px solid #0369a1;
    font-size: 8pt;
    color: #64748b;
  }
  .doc-footer .institution { font-weight: 600; color: #334155; }
  .doc-footer .footer-row { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 6px; }
  .doc-footer .footer-address { text-align: center; font-size: 7.5pt; color: #94a3b8; margin-top: 4px; }

  /* PRINT MEDIA */
  @media print {
    body { padding: 0; background: #fff; }
    .no-print, nav, .sidebar, button, .toaster, [data-sonner-toaster] { display: none !important; }
    .doc-header { page-break-inside: avoid; }
    .signature, .doc-footer { page-break-inside: avoid; }
    img { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  }
</style>`;
}

export const institutionalCSS = buildInstitutionalCSS();

/** Header HTML — 3 logos com central acima do texto institucional */
export function docHeader(title: string, config: DocumentConfig, extraRight?: string): string {
  const logoLeft = resolveLogoUrl(config.logoEsquerda, logoSmsFallback);
  const logoRight = resolveLogoUrl(config.logoDireita, logoCerFallback);
  const logoCentral = config.mostrarLogoCentral && config.logoCentral
    ? `<div class="logo-central"><img src="${config.logoCentral}" alt="Logo central" /></div>` : '';
  const linha3 = config.linha3 ? `<div class="extra-line">${config.linha3}</div>` : '';
  const linha4 = config.linha4 ? `<div class="extra-line">${config.linha4}</div>` : '';
  const now = new Date().toLocaleString('pt-BR');

  return `
    <div class="doc-header">
      <div class="logo-left">
        <img src="${logoLeft}" alt="Logo institucional esquerda" />
      </div>
      <div class="header-center">
        ${logoCentral}
        <h1>${config.linha1}</h1>
        ${config.linha2 ? `<div class="subtitle">${config.linha2}</div>` : ''}
        ${linha3}
        ${linha4}
      </div>
      <div class="logo-right">
        <img src="${logoRight}" alt="Logo institucional direita" />
      </div>
    </div>
    ${title ? `<div class="doc-title-bar">${title}</div>` : ''}
    <div class="doc-emit">${extraRight ? extraRight + ' &middot; ' : ''}Emitido em: ${now}</div>`;
}

export function docMeta(items: Record<string, string>): string {
  const entries = Object.entries(items).map(([k, v]) => `<strong>${k}:</strong> ${v}`).join(' &nbsp;|&nbsp; ');
  return `<div class="doc-meta">${entries}</div>`;
}

export function docFooter(config: DocumentConfig, extraInfo?: string): string {
  if (config.mostrarRodape === false) return '';
  const now = new Date().toLocaleString('pt-BR');
  const rodape = config.rodapeTexto || '';
  return `
    <div class="doc-footer">
      <div class="footer-row">
        <div class="institution">${config.linha1}${config.linha2 ? ' — ' + config.linha2 : ''}</div>
        <div>${rodape} ${extraInfo || ''}</div>
        <div>${now}</div>
      </div>
      ${config.rodapeEndereco ? `<div class="footer-address">${config.rodapeEndereco}</div>` : ''}
    </div>`;
}

/* =========================================================
 *  CARIMBO PROFISSIONAL — bloco final padronizado
 * ========================================================= */

export interface CarimboData {
  tipo?: 'digital' | 'imagem';
  nome: string;
  conselho: string;
  numero_registro: string;
  uf: string;
  especialidade: string;
  cargo: string;
  imagem_url: string;
  custom_data?: {
    cbo?: string;
    cns_profissional?: string;
    cidade_uf?: string;
    texto_complementar?: string;
    assinatura_url?: string;
    posicao?: 'left' | 'center' | 'right';
    mostrar_linha?: boolean;
    mostrar_nome?: boolean;
    mostrar_conselho?: boolean;
    mostrar_data_local?: boolean;
  };
}

/** Busca o carimbo do profissional logado (ou de um id específico) */
export async function loadCarimbo(profissionalId: string): Promise<CarimboData | null> {
  try {
    const { data } = await supabase
      .from('profissionais_carimbo')
      .select('*')
      .eq('profissional_id', profissionalId)
      .maybeSingle();
    return (data as any) || null;
  } catch {
    return null;
  }
}

/** Renderiza o bloco de carimbo/assinatura no padrão hospitalar */
export function docCarimbo(c: CarimboData | null, fallback?: { nome?: string; especialidade?: string }): string {
  if (!c && !fallback) return '';
  const cd = c?.custom_data || {};
  const posicao = cd.posicao || 'center';
  const mostrarLinha = cd.mostrar_linha !== false;
  const mostrarNome = cd.mostrar_nome !== false;
  const mostrarConselho = cd.mostrar_conselho !== false;
  const mostrarDataLocal = cd.mostrar_data_local === true;

  const nome = (c?.nome || fallback?.nome || '').toUpperCase();
  const especialidade = c?.especialidade || fallback?.especialidade || '';
  const conselho = c?.conselho || '';
  const numero = c?.numero_registro || '';
  const uf = c?.uf || '';
  const conselhoStr = [conselho, numero].filter(Boolean).join(' ') + (uf ? `/${uf}` : '');
  const cbo = cd.cbo || '';
  const cns = cd.cns_profissional || '';
  const cidadeUf = cd.cidade_uf || '';
  const textoCompl = cd.texto_complementar || '';
  const dataLocal = mostrarDataLocal
    ? `${cidadeUf || ''}${cidadeUf ? ', ' : ''}${new Date().toLocaleDateString('pt-BR')}`
    : '';

  const usaImagem = c?.tipo === 'imagem' && c?.imagem_url;
  const assinaturaImg = cd.assinatura_url ? `<img class="assinatura-img" src="${cd.assinatura_url}" alt="Assinatura" />` : '';

  return `
    <div class="signature pos-${posicao}">
      ${dataLocal ? `<div class="extra" style="margin-bottom:30px;">${dataLocal}</div>` : ''}
      ${assinaturaImg}
      ${mostrarLinha ? '<div class="signature-line"></div>' : ''}
      ${mostrarNome && nome ? `<div class="name">${nome}</div>` : ''}
      ${especialidade ? `<div class="role">${especialidade}${c?.cargo ? ' — ' + c.cargo : ''}</div>` : ''}
      ${mostrarConselho && conselhoStr.trim() ? `<div class="conselho">${conselhoStr}</div>` : ''}
      ${cbo ? `<div class="cbo">CBO: ${cbo}</div>` : ''}
      ${cns ? `<div class="cbo">CNS: ${cns}</div>` : ''}
      ${textoCompl ? `<div class="extra">${textoCompl}</div>` : ''}
      ${usaImagem ? `<img class="carimbo-img" src="${c.imagem_url}" alt="Carimbo" />` : ''}
    </div>`;
}

/** Helper combinado: carrega carimbo do profissional e renderiza */
export async function docCarimboFor(profissionalId: string, fallback?: { nome?: string; especialidade?: string }): Promise<string> {
  const c = await loadCarimbo(profissionalId);
  return docCarimbo(c, fallback);
}

/** Open a print window with full institutional layout */
export async function openPrintDocument(title: string, body: string, meta?: Record<string, string>): Promise<void> {
  const config = await loadDocumentConfig();
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  const metaHtml = meta ? docMeta(meta) : '';
  const css = buildInstitutionalCSS(config);

  printWindow.document.write(`<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <title>${title} — ${config.linha1}</title>
  ${css}
</head>
<body>
  ${docHeader(title, config)}
  ${metaHtml}
  <div class="doc-content">
    ${body}
  </div>
  ${docFooter(config)}
</body>
</html>`);
  printWindow.document.close();
  setTimeout(() => { printWindow.focus(); printWindow.print(); }, 400);
}
