/**
 * Shared institutional print/PDF layout for SMS Oriximiná.
 * All documents generated by the system use this template
 * to ensure consistent branding across screen, PDF, and print.
 */

import { supabase } from '@/integrations/supabase/client';
import logoSmsFallback from '@/assets/logo-sms-oriximina.jpeg';
import logoCerFallback from '@/assets/logo-cer-ii.webp';

export interface DocumentTypography {
  fonte: string;          // 'Arial' | 'Times New Roman' | 'Calibri' | 'Inter'
  tamanhoBase: number;    // 10..14 (corpo)
  tamanhoTitulo: number;  // 14..20
  espacamento: number;    // 1 | 1.15 | 1.5
  alinhamento: 'justify' | 'left' | 'center';
}

export interface DocumentMargins {
  superior: number; // mm
  inferior: number;
  esquerda: number;
  direita: number;
}

export interface LogoSlotConfig {
  altura: number;   // px (height): 30..140
  redonda: boolean; // recorte circular (aspect 1:1 + object-fit: cover)
  ativo: boolean;   // false = não renderiza no cabeçalho
}

export interface DocumentConfig {
  logoEsquerda: string;
  logoCentral: string;
  logoDireita: string;
  mostrarLogoCentral: boolean;
  mostrarLogos: boolean;
  logosConfig: {
    esquerda: LogoSlotConfig;
    central: LogoSlotConfig;
    direita: LogoSlotConfig;
  };
  linha1: string;
  linha2: string;
  linha3: string;
  linha4: string;
  rodapeTexto: string;
  rodapeEndereco: string;
  tipografia: DocumentTypography;
  margens: DocumentMargins;
  mostrarLinhaDivisoria: boolean;
  mostrarRodape: boolean;
}

const DEFAULT_TYPOGRAPHY: DocumentTypography = {
  fonte: 'Times New Roman',
  tamanhoBase: 12,
  tamanhoTitulo: 14,
  espacamento: 1.5,
  alinhamento: 'justify',
};

const DEFAULT_MARGINS: DocumentMargins = {
  superior: 30,
  inferior: 20,
  esquerda: 30,
  direita: 20,
};

const defaultSlot = (altura: number, ativo = true): LogoSlotConfig => ({ altura, redonda: false, ativo });

export const DEFAULT_CONFIG: DocumentConfig = {
  logoEsquerda: '',
  logoCentral: '',
  logoDireita: '',
  mostrarLogoCentral: false,
  mostrarLogos: true,
  logosConfig: {
    esquerda: defaultSlot(70, true),
    central: defaultSlot(72, false),
    direita: defaultSlot(70, true),
  },
  linha1: 'SECRETARIA MUNICIPAL DE SAÚDE DE ORIXIMINÁ',
  linha2: 'CENTRO ESPECIALIZADO EM REABILITAÇÃO NÍVEL II',
  linha3: '',
  linha4: '',
  rodapeTexto: '',
  rodapeEndereco: 'Rua Barão do Rio Branco, S/N, Santa Terezinha, Oriximiná-PA, 68270-000',
  tipografia: { ...DEFAULT_TYPOGRAPHY },
  margens: { ...DEFAULT_MARGINS },
  mostrarLinhaDivisoria: true,
  mostrarRodape: true,
};

let _cachedConfig: DocumentConfig | null = null;
let _cacheTimestamp = 0;
const CACHE_TTL = 60_000;

function clampAltura(n: any, fallback: number): number {
  const v = Number(n);
  if (!Number.isFinite(v)) return fallback;
  return Math.max(30, Math.min(140, Math.round(v)));
}
function mergeSlot(raw: any, defaults: LogoSlotConfig): LogoSlotConfig {
  return {
    altura: clampAltura(raw?.altura, defaults.altura),
    redonda: raw?.redonda === true,
    ativo: raw?.ativo !== undefined ? raw.ativo === true : defaults.ativo,
  };
}

function mergeConfig(raw: any): DocumentConfig {
  if (!raw) return { ...DEFAULT_CONFIG, logosConfig: { ...DEFAULT_CONFIG.logosConfig } };
  const lc = raw.logosConfig || {};
  const centralLegado = raw.cabecalho?.mostrarLogoCentral ?? raw.mostrarLogoCentral ?? false;
  return {
    logoEsquerda: raw.cabecalho?.logoEsquerda || raw.cabecalho?.logoUrl || raw.logoEsquerda || '',
    logoCentral: raw.cabecalho?.logoCentral || raw.logoCentral || '',
    logoDireita: raw.cabecalho?.logoDireita || raw.logoDireita || '',
    mostrarLogoCentral: centralLegado,
    mostrarLogos: raw.mostrarLogos !== false,
    logosConfig: {
      esquerda: mergeSlot(lc.esquerda, DEFAULT_CONFIG.logosConfig.esquerda),
      central: mergeSlot(lc.central, { ...DEFAULT_CONFIG.logosConfig.central, ativo: centralLegado }),
      direita: mergeSlot(lc.direita, DEFAULT_CONFIG.logosConfig.direita),
    },
    linha1: raw.cabecalho?.linha1 || raw.linha1 || DEFAULT_CONFIG.linha1,
    linha2: raw.cabecalho?.linha2 || raw.linha2 || DEFAULT_CONFIG.linha2,
    linha3: raw.cabecalho?.linha3 || raw.linha3 || '',
    linha4: raw.cabecalho?.linha4 || raw.linha4 || '',
    rodapeTexto: raw.rodapeTexto || '',
    rodapeEndereco: raw.rodapeEndereco || DEFAULT_CONFIG.rodapeEndereco,
    tipografia: { ...DEFAULT_TYPOGRAPHY, ...(raw.tipografia || {}) },
    margens: { ...DEFAULT_MARGINS, ...(raw.margens || {}) },
    mostrarLinhaDivisoria: raw.mostrarLinhaDivisoria ?? true,
    mostrarRodape: raw.mostrarRodape ?? true,
  };
}

export async function loadDocumentConfig(): Promise<DocumentConfig> {
  if (_cachedConfig && Date.now() - _cacheTimestamp < CACHE_TTL) return _cachedConfig;
  try {
    const { data } = await supabase
      .from('system_config')
      .select('configuracoes')
      .eq('id', 'default')
      .maybeSingle();
    const cfg = (data?.configuracoes as any)?.config_impressao;
    _cachedConfig = mergeConfig(cfg);
  } catch {
    _cachedConfig = { ...DEFAULT_CONFIG };
  }
  _cacheTimestamp = Date.now();
  return _cachedConfig!;
}

export function invalidateDocumentConfigCache(): void {
  _cachedConfig = null;
  _cacheTimestamp = 0;
}

function resolveLogoUrl(configUrl: string, fallback: string): string {
  if (configUrl && (configUrl.startsWith('http') || configUrl.startsWith('/'))) return configUrl;
  return fallback;
}

function escapeCssString(s: string): string {
  return String(s || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, ' ')
    .replace(/\r/g, '');
}

export function buildInstitutionalCSS(config?: DocumentConfig): string {
  const t = config?.tipografia || DEFAULT_TYPOGRAPHY;
  const m = config?.margens || DEFAULT_MARGINS;
  const showFooter = config?.mostrarRodape !== false;
  // Espaço reservado no @page para os @bottom-* boxes desenharem o rodapé
  // institucional. Se rodapé desativado, usa a margem inferior configurada.
  const printBottomMargin = showFooter ? Math.max(m.inferior, 20) : m.inferior;

  const fontFamily =
    t.fonte === 'Times New Roman' ? `'Times New Roman', Times, serif`
    : t.fonte === 'Calibri' ? `Calibri, 'Segoe UI', Arial, sans-serif`
    : t.fonte === 'Inter' ? `Inter, system-ui, Arial, sans-serif`
    : `Arial, 'Helvetica Neue', Helvetica, sans-serif`;

  // Textos do rodapé impressos via @page margin boxes (única técnica que
  // NÃO sobrepõe conteúdo em documentos multi-página no Chrome/Edge).
  const linhaInstitucional = [config?.linha1, config?.linha2].filter(Boolean).join(' — ');
  const enderecoRodape = config?.rodapeEndereco || '';
  const rodapeExtra = config?.rodapeTexto || '';

  const pageMarginBoxes = showFooter ? `
    @bottom-left {
      content: "${escapeCssString(enderecoRodape)}";
      font-family: ${fontFamily};
      font-size: 7pt;
      color: #94a3b8;
      padding-top: 4mm;
      vertical-align: top;
    }
    @bottom-center {
      content: "${escapeCssString(linhaInstitucional)}${rodapeExtra ? ' · ' + escapeCssString(rodapeExtra) : ''}";
      font-family: ${fontFamily};
      font-size: 7.5pt;
      color: #64748b;
      padding-top: 4mm;
      vertical-align: top;
    }
    @bottom-right {
      content: "Pág. " counter(page) "/" counter(pages);
      font-family: ${fontFamily};
      font-size: 7pt;
      color: #94a3b8;
      padding-top: 4mm;
      vertical-align: top;
    }
  ` : '';

  return `
<style>
  @page {
    size: A4;
    margin: ${m.superior}mm ${m.direita}mm ${printBottomMargin}mm ${m.esquerda}mm;
    ${pageMarginBoxes}
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  .doc-print-document {
    padding: 0;
    background: #fff;
    -webkit-text-size-adjust: 100%;
    text-size-adjust: 100%;
  }
  .doc-page {
    font-family: ${fontFamily};
    color: #1a1a1a;
    font-size: ${t.tamanhoBase}pt;
    line-height: ${t.espacamento};
    width: 100%;
    position: relative;
    overflow: visible;
  }

  /* HEADER */
  .doc-header {
    padding: 0 0 10px;
    margin-bottom: 10px;
    ${config?.mostrarLinhaDivisoria !== false ? 'border-bottom: 1.5px solid #0c4a6e;' : ''}
  }
  .doc-header .logos-row {
    display: flex;
    align-items: center;
    gap: 12px;
    width: 100%;
  }
  .doc-header .logos-row.cols-1 { justify-content: center; }
  .doc-header .logos-row.cols-2 { justify-content: space-between; }
  .doc-header .logos-row.cols-3 { justify-content: space-between; }
  .doc-header .logo-slot {
    display: flex;
    align-items: center;
  }
  .doc-header .logo-slot img {
    object-fit: contain;
  }
  .doc-header .header-text {
    text-align: center;
    margin-top: 6px;
    display: flex; flex-direction: column; align-items: center; gap: 1px;
  }
  .doc-header h1 {
    font-size: ${Math.max(t.tamanhoBase + 1, 12)}pt;
    font-weight: 700;
    text-transform: uppercase;
    color: #0c4a6e;
    margin: 0;
  }
  .doc-header .subtitle {
    font-size: ${t.tamanhoBase - 1}pt;
    font-weight: 600;
    color: #334155;
  }
  .doc-header .extra-line {
    font-size: 8pt;
    color: #475569;
  }
  .doc-title-bar {
    text-align: center;
    font-size: ${t.tamanhoTitulo}pt;
    font-weight: 700;
    text-transform: uppercase;
    color: #1a1a1a;
    margin: 4px 0 10px;
    padding: 4px 0;
    border-top: 1px solid #e2e8f0;
    border-bottom: 1px solid #e2e8f0;
  }
  .doc-emit {
    text-align: right;
    font-size: 7.5pt;
    color: #64748b;
    margin-bottom: 8px;
  }

  /* META INFO BAR */
  .doc-meta {
    font-size: 9pt;
    color: #334155;
    padding: 6px 10px;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 4px;
    margin-bottom: 12px;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 4px 12px;
  }
  .doc-meta strong { color: #1a1a1a; font-weight: 700; text-transform: uppercase; font-size: 8pt; }

  /* CONTENT */
  .doc-content {
    text-align: ${t.alinhamento};
    font-size: ${t.tamanhoBase}pt;
    line-height: ${t.espacamento};
    overflow: visible;
    overflow-wrap: break-word;
    word-break: normal;
    hyphens: auto;
  }

  .doc-content p,
  .doc-content div,
  .doc-content li,
  .doc-content td,
  .doc-content th {
    max-width: 100%;
    overflow: visible;
    overflow-wrap: break-word;
    word-break: normal;
  }

  .doc-content p {
    margin: 0 0 8pt;
    orphans: 3;
    widows: 3;
  }

  .doc-content ul,
  .doc-content ol {
    margin: 0 0 8pt 18pt;
    padding: 0;
  }

  .doc-content img {
    max-width: 100%;
    height: auto;
  }

  .doc-content [style*="white-space: nowrap"],
  .doc-content [style*="white-space:nowrap"] {
    white-space: normal !important;
  }

  /* Bloco textual ABNT para documentos clínicos enviados/impressos. */
  .doc-abnt {
    font-family: 'Times New Roman', Times, serif !important;
    font-size: 12pt !important;
    line-height: 1.5 !important;
    text-align: justify !important;
    color: #111827;
  }

  .doc-abnt .abnt-text,
  .doc-abnt .abnt-text p,
  .doc-abnt .abnt-text div,
  .doc-abnt .abnt-text span,
  .doc-abnt .abnt-text li {
    font-family: 'Times New Roman', Times, serif !important;
    font-size: 12pt !important;
    line-height: 1.5 !important;
  }

  .doc-abnt .abnt-text p {
    text-indent: 1.25cm;
    margin: 0 0 6pt;
  }

  .doc-abnt .abnt-text h1,
  .doc-abnt .abnt-text h2,
  .doc-abnt .abnt-text h3,
  .doc-abnt .abnt-text h4,
  .doc-abnt .abnt-text table p,
  .doc-abnt .abnt-text .no-indent {
    text-indent: 0;
  }

  .doc-abnt .abnt-text table {
    page-break-inside: auto;
    break-inside: auto;
  }

  .doc-abnt .abnt-text tr,
  .doc-abnt .abnt-text thead,
  .doc-abnt .abnt-text tbody {
    page-break-inside: avoid;
    break-inside: avoid;
  }

  .content-block {
    margin-top: 12pt;
  }

  .doc-sign-footer {
    margin-top: 28pt;
    display: grid;
    grid-template-columns: 1fr;
    gap: 12pt;
    page-break-inside: avoid;
    break-inside: avoid;
  }

  .e-signature-box {
    border: 1px solid #cbd5e1;
    border-radius: 4px;
    padding: 7pt 9pt;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 8pt;
    line-height: 1.35;
    color: #334155;
    background: #f8fafc;
    page-break-inside: avoid;
    break-inside: avoid;
  }

  .e-signature-box .sig-title {
    font-weight: 700;
    color: #0c4a6e;
    margin-bottom: 3pt;
  }

  .e-signature-box .sig-legal {
    margin-top: 3pt;
    color: #64748b;
  }

  .carimbo-digital {
    display: inline-block;
    border: 1px solid #1e293b;
    border-radius: 4px;
    padding: 7pt 12pt;
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 9pt;
    line-height: 1.35;
  }

  .carimbo-digital .carimbo-nome {
    font-weight: 700;
    text-transform: uppercase;
  }

  .carimbo-digital .carimbo-info {
    color: #334155;
  }

  /* SECTIONS */
  .section { 
    margin-bottom: 4px; 
    page-break-inside: avoid; 
  }
  .section-title { 
    font-weight: 700; 
    font-size: 8pt; 
    text-transform: uppercase; 
    color: #0369a1; 
    border-bottom: 0.5px solid #0369a1; 
    padding-bottom: 0px; 
    margin-bottom: 1px; 
  }
  .section-content { 
    font-size: ${t.tamanhoBase}pt; 
    line-height: 1.15; 
    white-space: pre-wrap; 
    color: #1a1a1a; 
    text-align: justify;
  }

  /* GRID FOR INFO */
  .info-grid { 
    display: grid; 
    grid-template-columns: repeat(3, 1fr); 
    gap: 4px; 
    margin-bottom: 10px; 
    padding: 6px; 
    background: #f8fafc; 
    border: 1px solid #e2e8f0; 
    border-radius: 4px; 
  }
  .info-item { display: flex; flex-direction: column; }
  .info-label { font-weight: 700; font-size: 7pt; color: #64748b; text-transform: uppercase; }
  .info-value { font-size: ${t.tamanhoBase - 1}pt; color: #1a1a1a; font-weight: 500; }

  /* SIGNATURE / CARIMBO */
  .signature { 
    margin-top: 30px; 
    text-align: center; 
    page-break-inside: avoid;
  }
  .signature-line { 
    width: 280px; 
    border-top: 1px solid #1e293b; 
    margin: 4px auto 4px; 
  }
  .signature .name { 
    font-size: ${t.tamanhoBase}pt; 
    font-weight: 700; 
    text-transform: uppercase; 
  }
  .signature .role,
  .signature .conselho,
  .signature .cbo,
  .signature .extra { 
    font-size: 8.5pt; 
    color: #334155; 
    line-height: 1.2;
  }
  .signature .assinatura-img { 
    max-height: 60px; 
    max-width: 200px; 
    display: block; 
    margin: 0 auto 2px; 
    object-fit: contain; 
  }
  .carimbo-img { 
    max-height: 80px; 
    max-width: 220px; 
    object-fit: contain; 
    display: block; 
    margin: 4px auto 0; 
  }

  .signature.pos-left { text-align: left; }
  .signature.pos-left .signature-line { margin-left: 0; }
  .signature.pos-left .assinatura-img,
  .signature.pos-left .carimbo-img { margin-left: 0; }

  .signature.pos-right { text-align: right; }
  .signature.pos-right .signature-line { margin-right: 0; margin-left: auto; }
  .signature.pos-right .assinatura-img,
  .signature.pos-right .carimbo-img { margin-right: 0; margin-left: auto; }

  /* FOOTER — usado APENAS no preview em tela.
     Na impressão, o rodapé real é desenhado pelos @bottom-* boxes do @page,
     que reservam a margem inferior e nunca sobrepõem o conteúdo. */
  .doc-footer {
    width: 100%;
    margin-top: 24px;
    padding-top: 5px;
    border-top: 1px solid #cbd5e1;
    font-size: 7.5pt;
    color: #64748b;
    background: #fff;
  }
  .doc-footer .footer-line { text-align: center; line-height: 1.25; overflow-wrap: anywhere; }
  .doc-footer .footer-extra { margin-top: 1px; }
  .doc-footer .footer-address { text-align: center; font-size: 7pt; color: #94a3b8; margin-top: 2px; line-height: 1.2; overflow-wrap: anywhere; }

  /* TABLES */
  table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
  th, td { border: 1px solid #cbd5e1; padding: 4px 6px; text-align: left; font-size: 8.5pt; }
  th { background: #f1f5f9; font-weight: 700; color: #0f172a; }

  @media screen {
    .doc-print-document {
      min-height: 297mm;
      padding: ${m.superior}mm ${m.direita}mm ${m.inferior}mm ${m.esquerda}mm;
    }
  }

  @media print {
    html, body { background: #fff; margin: 0; padding: 0; width: auto; min-width: 0; }
    .doc-print-document { background: #fff; margin: 0; padding: 0 !important; display: block; }
    .doc-page { display: block; position: static; }
    .no-print, nav, .sidebar, button, .toaster, [data-sonner-toaster] { display: none !important; }
    .doc-header, .signature, .doc-sign-footer, .e-signature-box, .carimbo-digital { page-break-inside: avoid; break-inside: avoid; }
    /* O rodapé HTML fica apenas no preview de tela; na impressão é substituído
       pelos @bottom-* boxes do @page (evita sobreposição multi-página). */
    .doc-footer { display: none !important; }
    img { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  }

</style>`;
}


export const institutionalCSS = buildInstitutionalCSS();

export function docHeader(title: string, config: DocumentConfig, extraRight?: string): string {
  const slots = config.logosConfig;
  const logoLeftUrl = resolveLogoUrl(config.logoEsquerda, logoSmsFallback);
  const logoRightUrl = resolveLogoUrl(config.logoDireita, logoCerFallback);
  const logoCenterUrl = config.logoCentral;

  const showLeft = slots.esquerda.ativo && !!logoLeftUrl;
  const showRight = slots.direita.ativo && !!logoRightUrl;
  const showCenter = slots.central.ativo && !!logoCenterUrl;

  const renderImg = (url: string, alt: string, slot: LogoSlotConfig) => {
    const h = slot.altura;
    if (slot.redonda) {
      return `<img class="round" src="${url}" alt="${alt}" style="height:${h}px;width:${h}px;border-radius:50%;object-fit:cover;" />`;
    }
    return `<img src="${url}" alt="${alt}" style="height:${h}px;max-height:${h}px;max-width:${Math.round(h * 2.5)}px;" />`;
  };

  const parts: string[] = [];
  if (showLeft) parts.push(`<div class="logo-slot left">${renderImg(logoLeftUrl, 'Logo esquerda', slots.esquerda)}</div>`);
  if (showCenter) parts.push(`<div class="logo-slot center">${renderImg(logoCenterUrl, 'Logo central', slots.central)}</div>`);
  if (showRight) parts.push(`<div class="logo-slot right">${renderImg(logoRightUrl, 'Logo direita', slots.direita)}</div>`);

  const count = parts.length;
  const rowClass = `logos-row cols-${count || 1}`;
  const logosRow = count > 0 ? `<div class="${rowClass}">${parts.join('')}</div>` : '';

  const linha3 = config.linha3 ? `<div class="extra-line">${config.linha3}</div>` : '';
  const linha4 = config.linha4 ? `<div class="extra-line">${config.linha4}</div>` : '';
  const now = new Date().toLocaleString('pt-BR');

  return `
    <div class="doc-header">
      ${logosRow}
      <div class="header-text">
        <h1>${config.linha1}</h1>
        ${config.linha2 ? `<div class="subtitle">${config.linha2}</div>` : ''}
        ${linha3}
        ${linha4}
      </div>
    </div>
    ${title ? `<div class="doc-title-bar">${title}</div>` : ''}
    <div class="doc-emit">${extraRight ? extraRight + ' &middot; ' : ''}Emitido em: ${now}</div>`;
}

export function docMeta(items: Record<string, string>): string {
  const entries = Object.entries(items).map(([k, v]) => `<div><strong>${k}:</strong> ${v}</div>`).join('');
  return `<div class="doc-meta">${entries}</div>`;
}

export function docFooter(config: DocumentConfig, extraInfo?: string): string {
  if (config.mostrarRodape === false) return '';
  const now = new Date().toLocaleString('pt-BR');
  const rodape = config.rodapeTexto || '';
  const extraLine = [rodape, extraInfo, now].filter(Boolean).join(' · ');
  return `
    <div class="doc-footer">
      <div class="footer-line">${config.linha1}${config.linha2 ? ' — ' + config.linha2 : ''}</div>
      ${extraLine ? `<div class="footer-line footer-extra">${extraLine}</div>` : ''}
      ${config.rodapeEndereco ? `<div class="footer-address">${config.rodapeEndereco}</div>` : ''}
    </div>`;
}

export interface CarimboData {
  tipo?: 'digital' | 'imagem';
  nome: string;
  conselho: string;
  numero_registro: string;
  uf: string;
  especialidade: string;
  cargo: string;
  imagem_url: string;
  custom_data?: {
    cbo?: string;
    cns_profissional?: string;
    cidade_uf?: string;
    texto_complementar?: string;
    assinatura_url?: string;
    posicao?: 'left' | 'center' | 'right';
    mostrar_linha?: boolean;
    mostrar_nome?: boolean;
    mostrar_conselho?: boolean;
    mostrar_data_local?: boolean;
  };
}

export async function loadCarimbo(profissionalId: string): Promise<CarimboData | null> {
  try {
    const { data } = await supabase
      .from('profissionais_carimbo')
      .select('*')
      .eq('profissional_id', profissionalId)
      .maybeSingle();
    return (data as any) || null;
  } catch {
    return null;
  }
}

export function docCarimbo(c: CarimboData | null, fallback?: { nome?: string; especialidade?: string; conselho?: string; numero_registro?: string; uf?: string }): string {
  if (!c && !fallback) return '';
  const cd = c?.custom_data || {};
  const posicao = cd.posicao || 'center';
  const mostrarLinha = cd.mostrar_linha !== false;
  const mostrarNome = cd.mostrar_nome !== false;
  const mostrarConselho = cd.mostrar_conselho !== false;
  const mostrarDataLocal = cd.mostrar_data_local === true;

  const nome = (c?.nome || fallback?.nome || '').toUpperCase();
  const especialidade = c?.especialidade || fallback?.especialidade || '';
  const conselho = c?.conselho || fallback?.conselho || '';
  const numero = c?.numero_registro || fallback?.numero_registro || '';
  const uf = c?.uf || fallback?.uf || '';
  const conselhoStr = [conselho, numero].filter(Boolean).join(' ') + (uf ? `/${uf}` : '');
  const cbo = cd.cbo || '';
  const cns = cd.cns_profissional || '';
  const cidadeUf = cd.cidade_uf || '';
  const textoCompl = cd.texto_complementar || '';
  const dataLocal = mostrarDataLocal
    ? `${cidadeUf || ''}${cidadeUf ? ', ' : ''}${new Date().toLocaleDateString('pt-BR')}`
    : '';

  const usaImagem = c?.tipo === 'imagem' && c?.imagem_url;
  const assinaturaImg = cd.assinatura_url ? `<img class="assinatura-img" src="${cd.assinatura_url}" alt="Assinatura" />` : '';

  return `
    <div class="signature pos-${posicao}">
      ${dataLocal ? `<div class="extra" style="margin-bottom:20px;">${dataLocal}</div>` : ''}
      ${assinaturaImg}
      ${mostrarLinha ? '<div class="signature-line"></div>' : ''}
      ${mostrarNome && nome ? `<div class="name">${nome}</div>` : ''}
      ${especialidade ? `<div class="role">${especialidade}${c?.cargo ? ' — ' + c.cargo : ''}</div>` : ''}
      ${mostrarConselho && conselhoStr.trim() ? `<div class="conselho">${conselhoStr}</div>` : ''}
      ${cbo ? `<div class="cbo">CBO: ${cbo}</div>` : ''}
      ${cns ? `<div class="cbo">CNS: ${cns}</div>` : ''}
      ${textoCompl ? `<div class="extra">${textoCompl}</div>` : ''}
      ${usaImagem ? `<img class="carimbo-img" src="${c.imagem_url}" alt="Carimbo" />` : ''}
    </div>`;
}

export async function docCarimboFor(profissionalId: string, fallback?: { nome?: string; especialidade?: string; conselho?: string; numero_registro?: string; uf?: string }): Promise<string> {
  const c = await loadCarimbo(profissionalId);
  return docCarimbo(c, fallback);
}

export function buildDocumentShell(
  title: string,
  bodyHtml: string,
  config: DocumentConfig,
  meta?: Record<string, string>,
): string {
  const metaHtml = meta ? docMeta(meta) : '';
  const css = buildInstitutionalCSS(config);
  return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <title>${title} — ${config.linha1}</title>
  ${css}
</head>
<body class="doc-print-document">
  <div class="doc-page">
    ${docHeader(title, config)}
    ${metaHtml}
    <div class="doc-content">
      ${bodyHtml}
    </div>
    ${docFooter(config)}
  </div>
</body>
</html>`;
}

export async function openPrintDocument(title: string, body: string, meta?: Record<string, string>): Promise<void> {
  const config = await loadDocumentConfig();
  printViaIframe(buildDocumentShell(title, body, config, meta));
}

export function printViaIframe(html: string): void {
  try {
    document.querySelectorAll('iframe[data-print-iframe="1"]').forEach(el => {
      try { el.parentNode?.removeChild(el); } catch {}
    });

    const MAX_BYTES = 8 * 1024 * 1024;
    if (html.length > MAX_BYTES) {
      console.warn('[printViaIframe] documento muito grande:', html.length, 'bytes');
      return;
    }

    const iframe = document.createElement('iframe');
    iframe.setAttribute('aria-hidden', 'true');
    iframe.setAttribute('data-print-iframe', '1');
    iframe.style.position = 'fixed';
    iframe.style.left = '-10000px';
    iframe.style.top = '0';
    iframe.style.width = '210mm';
    iframe.style.height = '297mm';
    iframe.style.border = '0';
    iframe.style.opacity = '0';
    iframe.style.pointerEvents = 'none';
    iframe.style.zIndex = '-1';
    iframe.srcdoc = html;
    document.body.appendChild(iframe);

    let printed = false;
    const cleanup = () => {
      try {
        iframe.srcdoc = '';
        iframe.src = 'about:blank';
      } catch {}
      try { document.body.removeChild(iframe); } catch {}
    };

    const triggerPrint = async () => {
      if (printed) return;
      printed = true;
      try {
        const win = iframe.contentWindow;
        if (!win) { cleanup(); return; }
        const doc = iframe.contentDocument as any;
        try { if (doc?.fonts?.ready) await doc.fonts.ready; } catch {}
        await new Promise<void>(resolve => win.requestAnimationFrame(() => win.requestAnimationFrame(() => resolve())));
        win.focus();
        win.print();
        const afterprint = () => { cleanup(); try { win.removeEventListener('afterprint', afterprint); } catch {} };
        try { win.addEventListener('afterprint', afterprint); } catch {}
        setTimeout(cleanup, 30_000);
      } catch {
        cleanup();
      }
    };

    iframe.addEventListener('load', () => {
      const doc = iframe.contentDocument;
      const imgs = doc ? Array.from(doc.images || []) : [];
      if (imgs.length === 0) {
        setTimeout(triggerPrint, 200);
        return;
      }
      let pending = imgs.length;
      const done = () => { if (--pending <= 0) setTimeout(triggerPrint, 120); };
      imgs.forEach(img => {
        if ((img as HTMLImageElement).complete) { done(); }
        else {
          img.addEventListener('load', done, { once: true });
          img.addEventListener('error', done, { once: true });
        }
      });
      setTimeout(triggerPrint, 4000);
    }, { once: true });

    setTimeout(triggerPrint, 6000);
  } catch (err) {
    console.error('[printViaIframe] erro:', err);
  }
}
