// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.1.0";

// src/lib/mcp/tools/search-patients.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (value) => typeof value === "string" && value.trim().startsWith("sb_publishable_")
        );
        if (key) return key.trim();
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("A Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("A verified OAuth token is required");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function getStaffScope(ctx) {
  if (!ctx.isAuthenticated()) throw new Error("Not authenticated");
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("funcionarios").select("id, usuario, unidade_id, ativo").eq("auth_user_id", ctx.getUserId()).eq("ativo", true).maybeSingle();
  if (error) throw new Error(`Could not verify staff access: ${error.message}`);
  if (!data) throw new Error("This account does not have an active staff profile");
  return {
    supabase,
    unidadeId: data.usuario === "admin.sms" ? null : data.unidade_id || null
  };
}

// src/lib/mcp/tools/search-patients.ts
var search_patients_default = defineTool({
  name: "search_patients",
  title: "Buscar pacientes",
  description: "Busca pacientes pelo nome dentro da unidade permitida ao usu\xE1rio conectado.",
  inputSchema: {
    name: z.string().trim().min(2).max(120).describe("Nome ou parte do nome do paciente."),
    limit: z.number().int().min(1).max(20).default(10).describe("M\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, limit }, ctx) => {
    try {
      const { supabase, unidadeId } = await getStaffScope(ctx);
      let query = supabase.from("pacientes").select("id, nome, data_nascimento, unidade_id").ilike("nome", `%${name.replace(/[%_]/g, "")} %`.replace(" %", "%")).order("nome").limit(limit);
      if (unidadeId) query = query.eq("unidade_id", unidadeId);
      const { data, error } = await query;
      if (error) throw error;
      const patients = data ?? [];
      return {
        content: [{ type: "text", text: patients.length ? JSON.stringify(patients) : "Nenhum paciente encontrado." }],
        structuredContent: { patients }
      };
    } catch (error) {
      throw new ToolError(error instanceof Error ? error.message : "Falha ao buscar pacientes");
    }
  }
});

// src/lib/mcp/tools/get-daily-agenda.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z as z2 } from "npm:zod@^4.6.5";
var get_daily_agenda_default = defineTool2({
  name: "get_daily_agenda",
  title: "Consultar agenda di\xE1ria",
  description: "Lista os agendamentos de uma data dentro da unidade permitida ao usu\xE1rio conectado.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data no formato AAAA-MM-DD."),
    professional_id: z2.string().uuid().optional().describe("ID opcional do profissional.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, professional_id }, ctx) => {
    try {
      const { supabase, unidadeId } = await getStaffScope(ctx);
      let query = supabase.from("agendamentos").select("id, paciente_id, paciente_nome, profissional_id, profissional_nome, data, hora, turno, status, tipo, nome_procedimento").eq("data", date).order("hora").limit(500);
      if (unidadeId) query = query.eq("unidade_id", unidadeId);
      if (professional_id) query = query.eq("profissional_id", professional_id);
      const { data, error } = await query;
      if (error) throw error;
      const appointments = data ?? [];
      return {
        content: [{ type: "text", text: appointments.length ? JSON.stringify(appointments) : "Nenhum agendamento encontrado." }],
        structuredContent: { appointments }
      };
    } catch (error) {
      throw new ToolError2(error instanceof Error ? error.message : "Falha ao consultar a agenda");
    }
  }
});

// src/lib/mcp/tools/get-patient-appointments.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z as z3 } from "npm:zod@^4.6.5";
var get_patient_appointments_default = defineTool3({
  name: "get_patient_appointments",
  title: "Consultar hist\xF3rico de agendamentos",
  description: "Consulta os agendamentos recentes de um paciente dentro da unidade permitida.",
  inputSchema: {
    patient_id: z3.string().min(1).max(100).describe("ID do paciente retornado pela busca."),
    limit: z3.number().int().min(1).max(50).default(10).describe("M\xE1ximo de agendamentos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, limit }, ctx) => {
    try {
      const { supabase, unidadeId } = await getStaffScope(ctx);
      let patientQuery = supabase.from("pacientes").select("id, nome, unidade_id").eq("id", patient_id);
      if (unidadeId) patientQuery = patientQuery.eq("unidade_id", unidadeId);
      const { data: patient, error: patientError } = await patientQuery.maybeSingle();
      if (patientError) throw patientError;
      if (!patient) throw new ToolError3("Paciente n\xE3o encontrado na unidade permitida.");
      let query = supabase.from("agendamentos").select("id, data, hora, turno, profissional_nome, status, tipo, nome_procedimento, tipo_falta").eq("paciente_id", patient_id).order("data", { ascending: false }).order("hora", { ascending: false }).limit(limit);
      if (unidadeId) query = query.eq("unidade_id", unidadeId);
      const { data, error } = await query;
      if (error) throw error;
      const appointments = data ?? [];
      return {
        content: [{ type: "text", text: JSON.stringify({ patient: patient.nome, appointments }) }],
        structuredContent: { patient, appointments }
      };
    } catch (error) {
      if (error instanceof ToolError3) throw error;
      throw new ToolError3(error instanceof Error ? error.message : "Falha ao consultar o hist\xF3rico");
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "ygbgywglxsshkkoiriul";
var mcp_default = defineMcp({
  name: "agendamento-saude-oriximina",
  title: "AGENDAMENTO SA\xDADE ORIXIMIN\xC1",
  version: "0.1.0",
  instructions: "Ferramentas somente leitura para localizar pacientes e consultar agendas. Respeite a unidade e as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_patients_default, get_daily_agenda_default, get_patient_appointments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.1.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
