-- Primeiro, desativamos todos os CBOs existentes para garantir uma limpeza completa,
-- mas mantemos a tabela caso haja referências de foreign key (embora o ideal seja atualizar os dados).
-- Como o pedido é "remover o anterior", vamos deletar os registros que não estão no novo padrão.

DELETE FROM public.cbo_codigos;

-- Inserção dos novos CBOs extraídos do PDF
INSERT INTO public.cbo_codigos (codigo, descricao, ativo, profissoes_relacionadas) VALUES
('515105', 'AGENTE COMUNITÁRIO DE SAÚDE', true, ARRAY['agente', 'saude']),
('515310', 'AGENTE DE AÇÃO SOCIAL', true, ARRAY['agente', 'social']),
('515140', 'AGENTE DE COMBATE ÀS ENDEMIAS', true, ARRAY['agente', 'endemias']),
('352210', 'AGENTE DE SAÚDE PÚBLICA', true, ARRAY['agente', 'saude', 'publica']),
('515130', 'AGENTE INDÍGENA DE SANEAMENTO', true, ARRAY['agente', 'indigena', 'saneamento']),
('515124', 'AGENTE INDÍGENA DE SAÚDE', true, ARRAY['agente', 'indigena', 'saude']),
('226310', 'ARTETERAPEUTA', true, ARRAY['arteterapeuta', 'arte']),
('411010', 'ASSISTENTE ADMINISTRATIVO', true, ARRAY['administrativo', 'assistente']),
('251605', 'ASSISTENTE SOCIAL', true, ARRAY['assistente', 'social']),
('322230', 'AUXILIAR DE ENFERMAGEM', true, ARRAY['enfermagem', 'auxiliar']),
('322250', 'AUXILIAR DE ENFERMAGEM DA ESTRATEGIA DE SAUDE DA FAMILIA', true, ARRAY['enfermagem', 'esf']),
('322415', 'AUXILIAR EM SAUDE BUCAL', true, ARRAY['bucal', 'auxiliar']),
('322430', 'AUXILIAR EM SAUDE BUCAL DA ESTRATEGIA DE SAUDE DA FAMILIA', true, ARRAY['bucal', 'esf']),
('223204', 'CIRURGIÃO DENTISTA - AUDITOR', true, ARRAY['dentista', 'auditor']),
('223208', 'CIRURGIÃO DENTISTA - CLÍNICO GERAL', true, ARRAY['dentista', 'clinico']),
('223280', 'CIRURGIÃO DENTISTA - DENTÍSTICA', true, ARRAY['dentista', 'dentistica']),
('223284', 'CIRURGIÃO DENTISTA - DISFUNÇÃO TEMPOROMANDIBULAR E DOR OROFACIAL', true, ARRAY['dentista', 'dor', 'orofacial']),
('223212', 'CIRURGIÃO DENTISTA - ENDODONTISTA', true, ARRAY['dentista', 'endodontista']),
('223216', 'CIRURGIÃO DENTISTA - EPIDEMIOLOGISTA', true, ARRAY['dentista', 'epidemiologista']),
('223220', 'CIRURGIÃO DENTISTA - ESTOMATOLOGISTA', true, ARRAY['dentista', 'estomatologista']),
('223224', 'CIRURGIÃO DENTISTA - IMPLANTODONTISTA', true, ARRAY['dentista', 'implantodontista']),
('223228', 'CIRURGIÃO DENTISTA - ODONTOGERIATRA', true, ARRAY['dentista', 'odontogeriatra']),
('223276', 'CIRURGIÃO DENTISTA - ODONTOLOGIA DO TRABALHO', true, ARRAY['dentista', 'trabalho']),
('223288', 'CIRURGIÃO DENTISTA - ODONTOLOGIA PARA PACIENTES COM NECESSIDADES ESPECIAIS', true, ARRAY['dentista', 'especiais']),
('223232', 'CIRURGIÃO DENTISTA - ODONTOLOGIA LEGAL', true, ARRAY['dentista', 'legal']),
('223236', 'CIRURGIÃO DENTISTA - ODONTOPEDIATRA', true, ARRAY['dentista', 'odontopediatra']),
('223240', 'CIRURGIÃO DENTISTA - ORTOPEDISTA E ORTODONTISTA', true, ARRAY['dentista', 'ortopedista']),
('223244', 'CIRURGIÃO DENTISTA - PATOLOGISTA BUCAL', true, ARRAY['dentista', 'patologista']),
('223248', 'CIRURGIÃO DENTISTA - PERIODONTISTA', true, ARRAY['dentista', 'periodontista']),
('223252', 'CIRURGIÃO DENTISTA - PROTESIÓLOGO BUCOMAXILOFACIAL', true, ARRAY['dentista', 'protesiologo']),
('223256', 'CIRURGIÃO DENTISTA - PROTESISTA', true, ARRAY['dentista', 'protesista']),
('223260', 'CIRURGIÃO DENTISTA - RADIOLOGISTA', true, ARRAY['dentista', 'radiologista']),
('223264', 'CIRURGIÃO DENTISTA - REABILITYADOR ORAL', true, ARRAY['dentista', 'reabilitador']),
('223268', 'CIRURGIÃO DENTISTA - TRAUMATOLOGISTA BUCOMAXILOFACIAL', true, ARRAY['dentista', 'traumatologista']),
('223272', 'CIRURGIÃO DENTISTA DE SAÚDE COLETIVA', true, ARRAY['dentista', 'coletiva']),
('223293', 'CIRURGIÃO-DENTISTA DA ESTRATÉGIA DE SAUDE DA FAMILIA', true, ARRAY['dentista', 'esf']),
('412110', 'DIGITADOR', true, ARRAY['digitador']),
('131205', 'DIRETOR DE SERVICOS DE SAUDE', true, ARRAY['diretor', 'saude']),
('515305', 'EDUCADOR SOCIAL', true, ARRAY['educador', 'social']),
('223505', 'ENFERMEIRO', true, ARRAY['enfermeiro']),
('223565', 'ENFERMEIRO DA ESTRATÉGIA DE SAÚDE DA FAMÍLIA', true, ARRAY['enfermeiro', 'esf']),
('223530', 'ENFERMEIRO DO TRABALHO', true, ARRAY['enfermeiro', 'trabalho']),
('223545', 'ENFERMEIRO OBSTÉTRICO', true, ARRAY['enfermeiro', 'obstetrico']),
('223550', 'ENFERMEIRO PSIQUIÁTRICO', true, ARRAY['enfermeiro', 'psiquiatrico']),
('223555', 'ENFERMEIRO PUERICULTOR E PEDIÁTRICO', true, ARRAY['enfermeiro', 'pediatrico']),
('223560', 'ENFERMEIRO SANITARISTA', true, ARRAY['enfermeiro', 'sanitarista']),
('226315', 'EQUOTERAPEUTA', true, ARRAY['equoterapeuta']),
('223405', 'FARMACÊUTICO', true, ARRAY['farmaceutico']),
('223415', 'FARMACÊUTICO ANALISTA CLÍNICO', true, ARRAY['farmaceutico', 'analista']),
('223430', 'FARMACÊUTICO EM SAÚDE PÚBLICA', true, ARRAY['farmaceutico', 'publica']),
('223445', 'FARMACÊUTICO HOSPITALAR E CLÍNICO', true, ARRAY['farmaceutico', 'hospitalar']),
('223425', 'FARMACÊUTICO PRÁTICAS INTEGRATIVAS E COMPLEMENTARES', true, ARRAY['farmaceutico', 'pics']),
('223650', 'FISIOTERAPEUTA ACUPUNTURISTA', true, ARRAY['fisioterapeuta', 'acupunturista']),
('223605', 'FISIOTERAPEUTA GERAL', true, ARRAY['fisioterapeuta']),
('223810', 'FONOAUDIÓLOGO', true, ARRAY['fonoaudiologo']),
('131210', 'GERENTE DE SERVICOS DE SAUDE', true, ARRAY['gerente', 'saude']),
('225105', 'MÉDICO ACUPUNTURISTA', true, ARRAY['medico', 'acupunturista']),
('225110', 'MÉDICO ALERGISTA E IMUNOLOGISTA', true, ARRAY['medico', 'alergista']),
('225154', 'MÉDICO ANTROPOSÓFICO', true, ARRAY['medico', 'antroposofico']),
('225120', 'MÉDICO CARDIOLOGISTA', true, ARRAY['medico', 'cardiologista']),
('225125', 'MÉDICO CLÍNICO', true, ARRAY['medico', 'clinico']),
('225142', 'MÉDICO DA ESTRATÉGIA DE SAÚDE DA FAMÍLIA', true, ARRAY['medico', 'esf']),
('225130', 'MÉDICO DE FAMILIA E COMUNIDADE', true, ARRAY['medico', 'familia']),
('225135', 'MÉDICO DERMATOLOGISTA', true, ARRAY['medico', 'dermatologista']),
('225140', 'MÉDICO DO TRABALHO', true, ARRAY['medico', 'trabalho']),
('225155', 'MÉDICO ENDOCRINOLOGISTA E METABOLOGISTA', true, ARRAY['medico', 'endocrinologista']),
('225160', 'MÉDICO FISIATRA', true, ARRAY['medico', 'fisiatra']),
('225165', 'MÉDICO GASTROENTEROLOGISTA', true, ARRAY['medico', 'gastro']),
('225170', 'MÉDICO GENERALISTA', true, ARRAY['medico', 'generalista']),
('225180', 'MÉDICO GERIATRA', true, ARRAY['medico', 'geriatra']),
('225250', 'MÉDICO GINECOLOGISTA E OBSTETRA', true, ARRAY['medico', 'ginecologista']),
('225185', 'MÉDICO HEMATOLOGISTA', true, ARRAY['medico', 'hematologista']),
('225195', 'MÉDICO HOMEOPATA', true, ARRAY['medico', 'homeopata']),
('225103', 'MÉDICO INFECTOLOGISTA', true, ARRAY['medico', 'infectologista']),
('225255', 'MÉDICO MASTOLOGISTA', true, ARRAY['medico', 'mastologista']),
('225109', 'MÉDICO NEFROLOGISTA', true, ARRAY['medico', 'nefrologista']),
('225350', 'MÉDICO NEUROFISIOLOGISTA CLÍNICO', true, ARRAY['medico', 'neurofisiologista']),
('225112', 'MÉDICO NEUROLOGISTA', true, ARRAY['medico', 'neurologista']),
('225118', 'MÉDICO NUTROLOGISTA', true, ARRAY['medico', 'nutrologista']),
('225265', 'MÉDICO OFTALMOLOGISTA', true, ARRAY['medico', 'oftalmologista']),
('225121', 'MÉDICO ONCOLOGISTA CLÍNICO', true, ARRAY['medico', 'oncologista']),
('225270', 'MÉDICO ORTOPEDISTA E TRAUMATOLOGISTA', true, ARRAY['medico', 'ortopedista']),
('225275', 'MÉDICO OTORRINOLARINGOLOGISTA', true, ARRAY['medico', 'otorrino']),
('225124', 'MÉDICO PEDIATRA', true, ARRAY['medico', 'pediatra']),
('225127', 'MÉDICO PNEUMOLOGISTA', true, ARRAY['medico', 'pneumo']),
('225133', 'MÉDICO PSIQUIATRA', true, ARRAY['medico', 'psiquiatra']),
('2231F9', 'MÉDICO RESIDENTE', true, ARRAY['medico', 'residente']),
('225136', 'MÉDICO REUMATOLOGISTA', true, ARRAY['medico', 'reumato']),
('225139', 'MÉDICO SANITARISTA', true, ARRAY['medico', 'sanitarista']),
('225285', 'MÉDICO UROLOGISTA', true, ARRAY['medico', 'urologista']),
('422215', 'MONITOR DE TELEATENDIMENTO', true, ARRAY['monitor', 'teleatendimento']),
('226305', 'MUSICOTERAPEUTA', true, ARRAY['musicoterapeuta']),
('226320', 'NATURÓLOGO', true, ARRAY['naturologo']),
('251545', 'NEUROPSICÓLOGO', true, ARRAY['neuropsicologo']),
('223710', 'NUTRICIONISTA', true, ARRAY['nutricionista']),
('422220', 'OPERADOR DE RADIO CHAMADA', true, ARRAY['operador', 'radio']),
('226110', 'OSTEOPATA', true, ARRAY['osteopata']),
('142340', 'OUVIDOR', true, ARRAY['ouvidor']),
('239415', 'PEDAGOGO', true, ARRAY['pedagogo']),
('234410', 'PROFESSOR DE EDUCAÇÃO FISICA NO ENSINO SUPERIOR', true, ARRAY['professor', 'educacao', 'fisica']),
('224140', 'PROFISSIONAL DE EDUCAÇÃO FISICA NA SAÚDE', true, ARRAY['educacao', 'fisica', 'saude']),
('251550', 'PSICANALISTA', true, ARRAY['psicanalista']),
('251555', 'PSICÓLOGO ACUPUNTURISTA', true, ARRAY['psicologo', 'acupunturista']),
('251510', 'PSICÓLOGO CLÍNICO', true, ARRAY['psicologo', 'clinico']),
('251540', 'PSICÓLOGO DO TRABALHO', true, ARRAY['psicologo', 'trabalho']),
('251505', 'PSICÓLOGO EDUCACIONAL', true, ARRAY['psicologo', 'educacional']),
('251530', 'PSICÓLOGO SOCIAL', true, ARRAY['psicologo', 'social']),
('239425', 'PSICOPEDAGOGO', true, ARRAY['psicopedagogo']),
('226105', 'QUIROPRAXISTA', true, ARRAY['quiropraxista']),
('422110', 'RECEPCIONISTA DE CONSULTÔRIO MÉDICO OU DENTÁRIO', true, ARRAY['recepcionista', 'consultorio']),
('422105', 'RECEPCIONISTA, EM GERAL', true, ARRAY['recepcionista']),
('322205', 'TECNICO DE ENFERMAGEM', true, ARRAY['enfermagem', 'tecnico']),
('322245', 'TECNICO DE ENFERMAGEM DA ESTRATEGIA DE SAUDE DA FAMILIA', true, ARRAY['enfermagem', 'esf']),
('322210', 'TECNICO DE ENFERMAGEM DE TERAPIA INTENSIVA', true, ARRAY['enfermagem', 'uti']),
('322255', 'TÉCNICO EM AGENTE COMUNITÂRIO DE SAUDE', true, ARRAY['agente', 'tecnico']),
('322405', 'TECNICO EM SAUDE BUCAL', true, ARRAY['bucal', 'tecnico']),
('322425', 'TÉCNICO EM SAUDE BUCAL DA ESTRATÉGIA DE SAUDE DA FAMILIA', true, ARRAY['bucal', 'esf']),
('422205', 'TELEFONISTA', true, ARRAY['telefonista']),
('422210', 'TELEOPERADOR', true, ARRAY['teleoperador']),
('223905', 'TERAPEUTA OCUPACIONAL', true, ARRAY['terapeuta', 'ocupacional']),
('515120', 'VISITADOR SANITÁRIO', true, ARRAY['visitador', 'sanitario']);
